/*
 * Copyright (C) 2016  Andy Walls <awalls.cx18@gmail.com>
 *
 * This file was automatically generated by gr_modtool from GNU Radio
 *
 * This file was automatically generated from a template incorporating
 * data input by Andy Walls.
 * See http://www.gnu.org/licenses/gpl-faq.en.html#GPLOutput .
 */

#ifndef INCLUDED_NWR_API_H
#define INCLUDED_NWR_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_nwr_EXPORTS
#  define NWR_API __GR_ATTR_EXPORT
#else
#  define NWR_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_NWR_API_H */
