/* -*- c++ -*- */
/*
 * Copyright (C) 2016  Andy Walls <awalls.cx18@gmail.com>
 *
 * This file was automatically generated by gr_modtool from GNU Radio
 *
 * This file was automatically generated from a template incorporating
 * data input by Andy Walls.
 * See http://www.gnu.org/licenses/gpl-faq.en.html#GPLOutput .
 */

#ifndef _QA_NWR_H_
#define _QA_NWR_H_

#include <gnuradio/attributes.h>
#include <cppunit/TestSuite.h>

//! collect all the tests for the gr-nwr directory

class __GR_ATTR_EXPORT qa_nwr
{
 public:
  //! return suite of tests for all of gr-nwr directory
  static CppUnit::TestSuite *suite();
};

#endif /* _QA_NWR_H_ */
