/*
 * Copyright (C) 2016  Andy Walls <awalls.cx18@gmail.com>
 *
 * This file was automatically generated by gr_modtool from GNU Radio
 *
 * This file was automatically generated from a template incorporating
 * data input by Andy Walls.
 * See http://www.gnu.org/licenses/gpl-faq.en.html#GPLOutput .
 */

/*
 * This class gathers together all the test cases for the gr-nwr
 * directory into a single test suite.  As you create new test cases,
 * add them here.
 */

#include "qa_nwr.h"

CppUnit::TestSuite *
qa_nwr::suite()
{
  CppUnit::TestSuite *s = new CppUnit::TestSuite("nwr");

  return s;
}
